config/routes.rb
Rails.application.routes.draw do
  root to: 'stocks#index'

  devise_for :users, controllers: {
    confrimations: 'confirmations'
  } do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
   
  resources :users, only: [:index, :show, :edit, :update, :create, :new, :destroy] 
  # do
  #   member do
  #     delete 'destroy'
  #   end
  # end
  
  resources :balance, only: [:show] do
    member do
      get 'deposit'
      get 'withdraw'
      patch 'confirm_deposit'
      patch 'confirm_withdrawal'
    end
  end
  
  resources :portfolios do
    member do
      get 'buy'
      get 'sell'
      patch 'confirm_sell'
    end
  end
  
  resources :trader_transactions, only: [:index, :show]
  resources :transactions
  resources :stocks, only: [:index, :show]
  resources :pending_requests, only: [:index, :update]
  #  do
    # member do
      # patch 'update'
    # end
  # end
  resources :declined_requests, only: [:index, :destroy]
end

app/models/stock.rb
class Stock < ApplicationRecord
    include IexAccessor
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  # before_action :set_stock, only: %i[ index, show ]
  before_action :authenticate_user!

  # GET /stocks or /stocks.json
  def index
    client = IEX::Api::Client.new(
      publishable_token: "pk_b3ce259e9e674fef8588c3da61ef3bf8",
      secret_token: 'sk_0316d9022ff64b7fa63b2f194df3559e',
      endpoint: 'https://cloud.iexapis.com/v1'
  )
    @stocks = Stock.all
    @quote = client.quote('AA')

    # quote.latest_price # 90.165
    # quote.change # 0.375
    # quote.change_percent # 0.00418
    # quote.change_percent_s
  end

  # GET /stocks/1 or /stocks/1.json
  def show
    @stock = Stock.find(params[:id])
  end


end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Blue Chip Stocks</h1>
    <%# <%= link_to 'New stock', new_stock_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
<div class="mx-auto mt-4 shadow mb-5 bg-body rounded w-[80%]">
    <div class="d-flex justify-content-evenly bg-dark text-light">
    </div>
    
    <div class="overflow-auto scroll text-center" >
        <table class="mx-auto" style="width:90%;">
            <thead class="position-sticky top-0 bg-white">

                <tr >
                    <th class="p-2"></th>
                    <th class="p-2">Symbol</th>
                    <th class="p-2">Change</th>
                    <th class="p-2">Price</th>
                </tr>

            </thead>

            <tbody class="mt-3 text-center">
                <% @stocks.each_with_index do | stock, index | %>
                                
                    <tr>
                        <td class="ps-2">
                            <%= index + 1%>
                        </td>
                                   
                        <td>
                            <%= link_to stock_path(stock.id), class: "btn btn-outline-light text-dark w-100 text-start fw-bold ps-2" do%>
                                <%= stock.stock_symbol %>
                            <%end%>
                            <p  style="--bs-text-opacity: .65;">
                                <%= stock.comp_name%>
                            </p>
                        </td>
                        <td>
                            <% if stock.access_quote.change_percent_s.include? "-" %>
                                <p class="w-100 text-start ps-2 fw-bold text-red-700" >
                                    <%= stock.access_quote.change_percent_s %>
                                </p>
                            <% else %>
                                <p class="w-100 text-start ps-2 fw-bold text-green-700" >
                                        <%= stock.access_quote.change_percent_s %>
                                </p>
                            <% end %>
                        </td>
                        <td>
                            <p class="text-dark w-100 text-start ps-2 fw-bold" >
                                <%= stock.access_quote.latest_price%>
                            </p>
                        </td>  
                    </tr>
                   
                <% end %>
            </tbody>         
        </table>        
    </div>
</div>
</div>

app/views/stocks/show.html.erb
<div class="p-0 mx-auto mt-5 shadow mb-5 bg-body rounded">
    <div class="bg-dark text-center" style="--bs-bg-opacity: .75;">
        <h4 class="mt-2 fw-bold text-white text-monospace">
            <%= @stock.stock_symbol %> 
        </h4> 
        <p>
            <%= @stock.comp_name %>
        </p>
        <%if @stock.access_quote.change_percent_s.include? "+" %>
            <span class="p-2 position-absolute top-0 end-0 mt-3 me-3">
                <%= @stock.access_quote.change_percent_s %>
            </span> 
        <% else %>
            <span class="p-2 position-absolute top-0 end-0 mt-3 me-3">
                <%= @stock.access_quote.change_percent_s %>
            </span> 
        <% end %>
        <div class="d-flex position-absolute bottom-0 mb-5 bg-white" style="width: 95%">
            <p class="fw-bold mx-2">
                $<%= @stock.access_quote.latest_price%>/ABBV
            </p>
            <p class="text-dark ps-3", style="--bs-text-opacity: 75;">
                <%= Time.now.strftime(" %B %d at %I:%M %p")%>
            </p>
        </div>
    </div>
    <div class="p-4 overflow-auto scroll" style="min-height: 20rem; max-height: 25rem;">
        <p style="text-align: justify; text-indent: 50px; font-size: 18px;">
            <%= @stock.comp_description %>
        </p>
    </div>
    <div>

        <%= link_to 'Buy Stock', buy_portfolio_path(:stocksymbol => @stock.stock_symbol), class: "rounded p-2 m-4 bg-green-600 text-white"%>
        <%= link_to 'Back', stocks_path, class: "ms-3"%>
        
    </div>
</div>