config/routes.rb
Rails.application.routes.draw do
  root to: 'stocks#index'

  devise_for :users, controllers: {
    confrimations: 'confirmations'
  } do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
   
  resources :users, only: [:index, :show, :edit, :update, :create, :new, :destroy] 
  # do
  #   member do
  #     delete 'destroy'
  #   end
  # end
  
  resources :balance, only: [:show] do
    member do
      get 'deposit'
      get 'withdraw'
      patch 'confirm_deposit'
      patch 'confirm_withdrawal'
    end
  end
  
  resources :portfolios do
    member do
      get 'buy'
      get 'sell'
      patch 'confirm_sell'
    end
  end
  
  resources :trader_transactions, only: [:index, :show]
  resources :transactions
  resources :stocks, only: [:index, :show]
  resources :pending_requests, only: [:index, :update]
  #  do
    # member do
      # patch 'update'
    # end
  # end
  resources :declined_requests, only: [:index, :destroy]
end

app/models/user.rb
class User < ApplicationRecord

  validates :email, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  # Setup accessible (or protected) attributes for your model
  enum role: [:trader, :admin]
  validates :balance, numericality: {greater_than_or_equal_to: 0}
  validates :state, presence: true
  STATE = ["Pending", "Declined", "Approved"]

  has_many :transactions, dependent: :destroy
  has_many :portfolios, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :verify_if_admin, only: [:index, :edit, :show, :create, :new]

  # GET /users or /users.json
  def index
    @users = User.where(role: "trader")
    @traders = @users.where(role: "trader", state: "Approved")
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.state = "Approved"
    @user.skip_confirmation!
    if @user.save
      redirect_to @user, notice: 'New trader was has been created successfully.'
    else
      render :new
    end

  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!
    redirect_to users_path, notice: "You successfully deleted #{@user.email}'s profile."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      # params.fetch(:user, {})
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

    def verify_if_admin
      if current_user.role == 'admin'
         return
      else
         redirect_to root_path, notice: "You must be an admin to perform this action."
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
  

    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="mt-5 ">
    <div class="mx-auto text-warning  text-dark">

        <h2 class="text-left bg-info bg-opacity-25">
            <%= user.email %>
            <span class='bg-dark rounded-pill position-absolute top-1 end-0 mx-3'>
                <%= user.portfolios.count %> stocks
            </span>
        </h2>
        <div class="overflow-auto ps-4" style="min-height: 20rem; max-height: 35rem;">

            <div class="flex">
                <strong>
                    Date Added:  
                </strong>
                <p class="ms-2">
                    <%= user.created_at.strftime("%A %B %d, %Y") %>
                </p>
            </div>
            <div class="flex">
                <strong>
                    Last profile update: 
                </strong>
                <p class="ms-2">
                    <%= user.updated_at.strftime("%A %B %d, %Y") %>
                </p>
            </div>
            <div class="flex">
                <strong>
                    Role:
                </strong>
                <p class="ms-2">
                    <%= user.role %>
                </p>
            </div>
            <div class="flex">
                <strong>
                    Total Transactions:
                </strong>
                <%= link_to  transaction_path(user) do%>
                    <%= user.transactions.count %>
                <% end %>   
            </div>
            <div class="flex">
                <strong>
                    Last Transaction:
                </strong>
                <p class="ms-2">
                    <% if user.transactions.last %>
                        <%= user.transactions.last.stock_symbol%>,
                        <% if user.transactions.last.transaction_type = 'buy' %>
                        Activity: Buy,
                        <% else %>
                        Activity: Sell,
                        <% end %>
                        <%= user.transactions.last.created_at.strftime("%A %B %d, %Y") %>
                    <%else%>
                        <h1>No transactions yet</h1>
                    <% end %>
                </p>
            </div>
            <div>
                <strong>
                    Stocks:
                </strong>
                <div class="ms-2">
                    <div class = "row overflow-auto" style="min-height: 10rem; max-height: 15rem;">
                    <%if user.portfolios.empty?%>
                    <h1 class="inline-block">No stocks in portfolio<h1>
                    <%else%>
                        <% user.portfolios.each do |stock| %>
                            
                        <div class="my-1 mx-auto col-5">
                
                            <div>        
                                <%= stock.stock_symbol %> 
                            </div>
                            
                            <div class="flex ">
                                <strong>Qty:</strong>
                                <%= stock.quantity %>
                            </div>  
                            
                            <div>
                                <%= stock.created_at.strftime("%A %B %d, %Y")%>
                            </div>
                        </div>                     
                        <% end %>
                    <% end %>
                    </div>
                </div>
            </div>             
        </div>
        <div>
            <%= link_to "Edit", edit_user_path(@user), class:"mx-3" %>
            <%= link_to "Delete",  user_path(@user), method: :delete, confirm: "Are you sure you want to delete #{user.email}'s profile?", class:"mx-3" %>
            <%= link_to "Back", users_path, class:"mx-3" %>
            
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Show this user", @user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">All Traders</h1>
    <%= link_to 'Add New Trader', new_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="users" class="min-w-full">
    <ul>
    <% @traders.each do |trader| %>
      <li>
          <%= link_to  trader.email, user_path(trader)%>
          
          <span class="ms-2 mt-2 col text-center">
            <%=  trader.role %> 
          </span>

          <span class="ms-2 col text-center btn btn-dark border rounded-pill">
             <%= trader.portfolios.count %> stocks
          </span>
      </li>
    <% end %>
  </ul>
  </div>
</div>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>

<div>
  <div class = "row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="rounded-3 mt-5">
        <div class="p-4 p-sm-5">        
          <div class="mb-3">
                <%= f.label :email %><br />
                <%= f.email_field :email, autofocus: true, autocomplete: "email", :class => "form-control" %>
          </div>
          <div class="mb-3">
            <%= f.label :password,:value => "New Password (#{@minimum_password_length} characters minimum)" %> <br />
            <%= f.password_field :password, autocomplete: "new-password", :class => "form-control", :placeholder => "******" %>
          </div>
          <div class="mb-3">
            <%= f.label :password_confirmation%><br />
            <%= f.password_field :password_confirmation, autocomplete: "new-password", :class => "form-control", :placeholder => "******" %>
          </div>

          <div class="d-grid mb-3 mt-4">
            <%= f.submit "Create", :class => "text-uppercase fw-bold" %>
          </div>

          <div class="d-grid mb-3 mt-4">
            <%= link_to "Back to Traders", users_path, class: "text-uppercase fw-bold" %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<div class="mx-auto">

  <%= render @user %>
    
</div>