config/routes.rb
Rails.application.routes.draw do
  root to: 'stocks#index'

  devise_for :users, controllers: {
    confrimations: 'confirmations'
  } do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
   
  resources :users, only: [:index, :show, :edit, :update, :create, :new, :destroy] 
  # do
  #   member do
  #     delete 'destroy'
  #   end
  # end
  
  resources :balance, only: [:show] do
    member do
      get 'deposit'
      get 'withdraw'
      patch 'confirm_deposit'
      patch 'confirm_withdrawal'
    end
  end
  
  resources :portfolios do
    member do
      get 'buy'
      get 'sell'
      patch 'confirm_sell'
    end
  end
  
  resources :trader_transactions, only: [:index, :show]
  resources :transactions
  resources :stocks, only: [:index, :show]
  resources :pending_requests, only: [:index, :update]
  #  do
    # member do
      # patch 'update'
    # end
  # end
  resources :declined_requests, only: [:index, :destroy]
end

app/controllers/declined_requests_controller.rb
class DeclinedRequestsController < ApplicationController
    def index
        @request =  User.where(role: "trader", state: "Declined").where.not(confirmed_at: nil).order(confirmed_at: :DESC)
    end

    def destroy
        @user = User.find(params[:id])
        
        if @user.destroy
          UserMailer.with(user: @user).destroy_account_email.deliver_now
          redirect_to declined_requests_path, notice: "You successfully deleted #{@user.email}'s application."
        end
    end
end

app/helpers/declined_requests_helper.rb
module DeclinedRequestsHelper
end

app/views/declined_requests/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="card mx-auto mt-5" >

  <div class="text-center">
    <h4>Declined Traders Requests</h4>
 
  </div>

  <ul class="overflow-auto container" style="min-height: 20rem; max-height: 35rem;">
    <% if @request.empty? %>
      <h4 class="text-center mt-5 text-secondary">There is currently no request yet.</h4>
    <% end %>
    <% @request.each do |request| %>
      <li class="d-flex justify-content-between p-3 row">
      
          <%= link_to  request.email, user_path(request), class: "btn btn-outline-light text-dark col"%>
          <span class="ms-2 col">
            <%=  request.state %> 
            <%=  request.role %> 
          </span>
          
          
          <div class="text-center btn-group col">

            <%= link_to "Delete",  declined_request_path(request), method: :delete, data: { confirm: "Are you sure you want to delete #{request.email}'s application?" }, class: "mx-2" %>
        
            <%= link_to "Approve", pending_request_path(request, state: "Approved"), method: :patch, class: " mx-2" %>
            
          </div>
      </li>
    <% end %>
  </ul>

  <div class="text-center">
  
    <%= link_to "Back to Pending Requests", pending_requests_path, class: "mx-2" %>
            
  </div>

</div>