config/routes.rb
Rails.application.routes.draw do
  root to: 'stocks#index'

  devise_for :users, controllers: {
    confrimations: 'confirmations'
  } do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
   
  resources :users, only: [:index, :show, :edit, :update, :create, :new, :destroy] 
  # do
  #   member do
  #     delete 'destroy'
  #   end
  # end
  
  resources :balance, only: [:show] do
    member do
      get 'deposit'
      get 'withdraw'
      patch 'confirm_deposit'
      patch 'confirm_withdrawal'
    end
  end
  
  resources :portfolios do
    member do
      get 'buy'
      get 'sell'
      patch 'confirm_sell'
    end
  end
  
  resources :trader_transactions, only: [:index, :show]
  resources :transactions
  resources :stocks, only: [:index, :show]
  resources :pending_requests, only: [:index, :update]
  #  do
    # member do
      # patch 'update'
    # end
  # end
  resources :declined_requests, only: [:index, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStockTradingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <nav class="w-full h-10 bg-gray-700 flex p-2 text-white justify-between">
      <h1 class="font-extrabold">Bull&Bear</h1>
        <% if current_user %>
          <% if current_user.role == 'admin' %>
            <ul class="flex w-[50%] justify-between">
              <li>
                <%= link_to 'Traders', users_path %>
              </li>

              <li>
                <%= link_to 'Requests', pending_requests_path%>
              </li>

              <li>
                <%= link_to 'Transactions', transactions_path%>
              </li>
              <div class="w-fit">Hi Admin, <%=current_user.email.split("@")[0]%>!</div>
            </ul>
          <% else %>
            <ul class="flex w-[70%] justify-between">
              <li>
                <%= link_to "Balance: #{current_user.balance}", balance_path(current_user)%>
              </li>
              <li><%=link_to 'Home', stocks_path%></li>
              <li><%=link_to 'Portfolio', portfolios_path%></li>
              <li><%=link_to 'Transactions', trader_transactions_path%></li>
              <div class="w-fit">Hi, <%=current_user.email.split("@")[0]%>!</div>
            </ul>
          <%end%>
                
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          
        <%else%>
          <%= link_to 'Sign up', new_user_registration_path %>
          <%= link_to 'Sign in', new_user_session_path%>
        <%end%>
     </nav>
      <p class="notice bg-slate-300 bg-white"><%= notice %></p> 
      <p class="alert bg-slate-300"><%= alert %></p> 

    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>